# .github/workflows/deploy.yml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GEOAPIFY_KEY: ${{ secrets.GEOAPIFY_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm run build
